### ISSUE TITLE
Set Project Tags, Docs and Informations

### ISSUE THREAD

**Issue by husamettinarabaci** [octoposprime/op-mo-app#2]

**Comment by husamettinarabaci** [comment]
This is a backlog issue. It will be complete in the future.

**Comment by Maraza25** [comment]
Genesis Code    React Native'in temel unsurlarını keşfedin.
Syntax Nexus    Temel sözdizimi ve yapıları öğrenin.
Component Cyberspace    Bileşenlerin oluşturulması ve kullanılmasına dair derinlemesine bilgi.
State Stream    Uygulamanızdaki durumu anlayın ve yönetin.
Propulsion Props    Prop'ları geçme ve manipüle etme tekniklerini öğrenin.
Hook Horizon    Fonksiyonel bileşenler için React hook'larını keşfedin.
Navigation Nebula    Gelişmiş yönlendirme ile ekranlar ve veri arasında gezinin.
Redux Realm    Durum yönetimi için Redux kullanımını gerçekleştirin.
Native Node    Yerel yetenekleri React Native ile entegre edin.
Launchpad Legends    Uygulamanızı App Store ve Google Play Store'a dağıtımının temellerini öğrenin.
