### ISSUE TITLE
Login Design

### ISSUE THREAD

**Issue by FurkanTansel** [octoposprime/op-mo-app#21]
The UI design of the login page will be created.

**Comment by Maraza25** [comment]
Please share the link of your design here

**Comment by mrezan12** [comment]
https://www.figma.com/file/44wDekcnF9Fx5Sx3o9L6uR/OCTOPOS-LOGIN-REGISTER?type=design&node-id=0-1&mode=design&t=xXriElwjZf1dSHvO-0
